packageExtensions:
  relay-compiler@*:
    dependencies:
      # yarn pnp와 호환
      # https://github.com/kriasoft/graphql-starter/blob/main/.yarnrc.yml
      relay-compiler-language-typescript: ^14.1.0

yarnPath: .yarn/releases/yarn-3.0.0.cjs
